apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node-app-v1
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30080 # expose externally
  selector:
    app: node-app-v1
